cloudforet-io/identity

- src/spaceone/identity/service/user_service.py
- add email_verified value when user created with reset_password option
* #31
> Add email_verified value when user created with reset_password option

- src/spaceone/identity/error/error_role.py
- src/spaceone/identity/model/user/request.py
- src/spaceone/identity/model/workspace_user/response.py
- src/spaceone/identity/service/role_binding_service.py
- src/spaceone/identity/service/role_service.py
- src/spaceone/identity/service/user_service.py
- add duplicated role binding check rule
> Add duplicated role binding check rule

- src/spaceone/identity/model/external_auth/response.py
- convert data type 'datetime' -> 'string' at ExternalAuthResponse
> Convert data type 'datetime' -> 'string' at ExternalAuthResponse

- src/spaceone/identity/connector/external_auth_plugin_connector.py
- src/spaceone/identity/manager/external_auth_manager.py
- src/spaceone/identity/manager/secret_manager.py
- src/spaceone/identity/manager/token_manager/external_token_manager.py
- src/spaceone/identity/service/domain_service.py
- src/spaceone/identity/service/external_auth_service.py
> Add unset ExternalAuth api

- src/spaceone/identity/service/token_service.py
- fix typo at required_action permissions
- '.' -> ':'
> Fix typo at required_action permissions

- src/spaceone/identity/manager/__init__.py
- src/spaceone/identity/manager/account_collector_plugin_manager.py
- src/spaceone/identity/service/trusted_account_service.py
- fix BaseDict' object has no attribute 'to_dict' error when sync …
* #199
> Fix BaseDict' object has no attribute 'to_dict' error when sync

- src/spaceone/identity/service/provider_service.py
- src/spaceone/identity/service/service_account_service.py
- fix provider plugin update api
* #199
> Fix provider plugin update api 

- src/spaceone/identity/model/agent/response.py
- src/spaceone/identity/service/agent_service.py
- src/spaceone/identity/service/job_service.py
- Remove duplicated workspace create logic
* #199
> Remove duplicated workspace create logic

- src/spaceone/identity/interface/grpc/project.py
- src/spaceone/identity/model/project/database.py
- src/spaceone/identity/model/project/request.py
- src/spaceone/identity/model/project/response.py
- src/spaceone/identity/model/service_account/database.py
- src/spaceone/identity/model/service_account/request.py
- src/spaceone/identity/model/service_account/response.py
- src/spaceone/identity/model/user_profile/response.py
- src/spaceone/identity/model/workspace/database.py
- src/spaceone/identity/model/workspace/request.py
- src/spaceone/identity/model/workspace/response.py
- src/spaceone/identity/service/project_service.py
- src/spaceone/identity/service/service_account_service.py
- src/spaceone/identity/service/workspace_service.py
- add dormant fields to workspace
- add dormant fields to service account
- remove user_groups from project
> Implement Dormant Features

- src/spaceone/identity/conf/global_conf.py
- src/spaceone/identity/manager/cost_analysis_manager.py
- src/spaceone/identity/manager/service_account_manager.py
- src/spaceone/identity/manager/workspace_manager.py
- src/spaceone/identity/model/service_account/database.py
- src/spaceone/identity/model/workspace/database.py
- src/spaceone/identity/service/job_service.py
> feat: implement dormancy features

- src/spaceone/identity/service/job_service.py
- Remove domain_id parameter when request to secret service
> Remove domain_id parameter when request to secret service

- src/spaceone/identity/manager/workspace_group_manager.py
- src/spaceone/identity/service/workspace_group_service.py
Delete role bindings when the workspace group is deleted
> Delete role bindings when the workspace group is deleted

- src/spaceone/identity/error/custom.py
- src/spaceone/identity/service/role_service.py
> Add safe delete role logic

- src/spaceone/identity/interface/grpc/workspace_group.py
- src/spaceone/identity/manager/role_binding_manager.py
- src/spaceone/identity/manager/workspace_group_manager.py
- src/spaceone/identity/model/workspace_group/database.py
- src/spaceone/identity/model/workspace_group/request.py
- src/spaceone/identity/model/workspace_group/response.py
- src/spaceone/identity/service/role_binding_service.py
- src/spaceone/identity/service/token_service.py
- src/spaceone/identity/service/workspace_group_service.py
Due to significant changes in the WorkspaceGroup API, the code has been modified and refactored accordingly.
> Update workspace group

- src/spaceone/identity/manager/workspace_group_manager.py
Modified to set `workspace_group_id: null` for Workspaces when a Workspace Group is deleted.
> Modify workspace group manager

- src/spaceone/identity/interface/grpc/workspace.py
- src/spaceone/identity/manager/workspace_manager.py
- src/spaceone/identity/model/workspace/request.py
- src/spaceone/identity/model/workspace/response.py
- src/spaceone/identity/service/workspace_service.py
If `workspace_group_id` is present, it corresponds to Add Workspace, and if `workspace_group_id` is absent, it corresponds to Remove Workspace.
> Add change_workspace_group api

- src/spaceone/identity/manager/workspace_group_manager.py
- src/spaceone/identity/service/user_profile_service.py
- src/spaceone/identity/service/workspace_group_service.py
- src/spaceone/identity/service/workspace_group_user_service.py
Refactor code and modify get_workspace_groups
> Refactor code and modify get_workspace_groups

- src/spaceone/identity/manager/workspace_group_manager.py
- src/spaceone/identity/manager/workspace_manager.py
- src/spaceone/identity/service/workspace_group_service.py
- src/spaceone/identity/service/workspace_service.py
Refactor code such that unify debug code
> Refactor code such that unify debug code

- src/spaceone/identity/manager/workspace_group_manager.py
- src/spaceone/identity/model/workspace_group/database.py
- src/spaceone/identity/model/workspace_group/response.py
- src/spaceone/identity/service/workspace_group_service.py
- src/spaceone/identity/service/workspace_group_user_service.py
- src/spaceone/identity/service/workspace_service.py
Add the workspace_count field to workspace_group and refactor the code
> Add the workspace_count field to workspace_group and refactor the code

- src/spaceone/identity/manager/workspace_manager.py
- src/spaceone/identity/model/workspace/database.py
- src/spaceone/identity/model/workspace/response.py
- src/spaceone/identity/service/workspace_service.py
Add changed_at to Workspace and modify the list of Workspace
> Add changed_at to Workspace and modify the list of Workspace

- src/spaceone/identity/service/workspace_service.py
Modify when deleting workspace A from Workspace GroupA, all role bindings are deleted to related to Workspace GroupA
> Modify when deleting workspace A from Workspace GroupA, all role bindings are deleted to related to Workspace GroupA

- src/spaceone/identity/service/user_profile_service.py
- src/spaceone/identity/service/workspace_group_service.py
- src/spaceone/identity/service/workspace_group_user_service.py
Change from dict type to object type
> Change from dict type to object type

- .gitignore
- src/spaceone/identity/manager/workspace_group_user_manager.py
- src/spaceone/identity/service/workspace_group_user_service.py
Modify code such that a user has an admin role type in case
> Modify code such that a user has an admin role type in case 

- src/spaceone/identity/manager/workspace_group_manager.py
- src/spaceone/identity/service/role_binding_service.py
- src/spaceone/identity/service/workspace_group_service.py
- src/spaceone/identity/service/workspace_group_user_service.py
> Refactor code for maintenance

- src/spaceone/identity/service/workspace_group_service.py
Fix add users when there is more than 1 workspace
> Fix add users when there is more than 1 workspace

- src/spaceone/identity/service/job_service.py
- fix error when creating secret_id is None during auto sync
> fix error when creating secret_id is None during auto sync

- src/spaceone/identity/service/user_service.py
- Add logic to delete user_secret when disabling MFA if mfa_type is OTP
> Add logic to delete user_secret when disabling MFA if mfa_type is OTP

- src/spaceone/identity/manager/secret_manager.py
- src/spaceone/identity/service/user_service.py
Fix permission error when deleting user_secret in user_service disable_mfa method
> Fix permission error when deleting user_secret in user_service disable_mfa method

- src/spaceone/identity/service/token_service.py
…auth_type with SAML protocol
refactor: Update MFA requirement to prevent enforcement for EXTERNAL auth_type with SAML protocol
> Update MFA requirement to prevent enforcement for EXTERNAL auth_type with SAML protocol

- src/spaceone/identity/model/service_account/database.py
- src/spaceone/identity/service/service_account_service.py
- fix update service_account_mgr_id error
> Fix update service_account_mgr_id error

- src/spaceone/identity/model/user/database.py
* set default value for tags field to an empty dictionary
> fix: set default value for tags field to an empty dictionary

- src/spaceone/identity/error/error_mfa.py
- src/spaceone/identity/manager/token_manager/mfa_token_manager.py
- src/spaceone/identity/service/role_binding_service.py
- src/spaceone/identity/service/token_service.py
- src/spaceone/identity/service/user_profile_service.py
- src/spaceone/identity/service/user_service.py
> feat: update MFA token issuance logic

- src/spaceone/identity/error/error_role.py
- src/spaceone/identity/model/user/request.py
- src/spaceone/identity/service/role_binding_service.py
Add error handling for role updates assigned by workspace groups
> Add error handling for role updates assigned by workspace groups

- src/spaceone/identity/manager/role_binding_manager.py
- src/spaceone/identity/manager/user_manager.py
- src/spaceone/identity/service/domain_service.py
- src/spaceone/identity/service/role_binding_service.py
- src/spaceone/identity/service/role_service.py
- src/spaceone/identity/service/system_service.py
- src/spaceone/identity/service/user_service.py
- src/spaceone/identity/service/workspace_group_service.py
- src/spaceone/identity/service/workspace_service.py
- Remove the rule that a workspace must always have one owner
- Check if the role exists when disabling a role
> reafactor: Remove the rule that a workspace must always have one owner
