cloudforet-io/identity

.github/PULL_REQUEST_TEMPLATE.md
src/spaceone/identity/error/error_service_account.py
src/spaceone/identity/info/service_account_info.py
src/spaceone/identity/model/service_account_model.py
src/spaceone/identity/service/service_account_service.py
test/factory/service_account_factory.py
test/service/test_service_account_service.py

feat: add service_account_type, trusted_service_account_id
etc: update test factory
etc: add PULL_REQUEST_TEMPLATE.md

feat: add service_account_type, trusted_service_account_id

---

src/spaceone/identity/model/service_account_model.py

fix: add default for ServiceAccount.scope

fix: add default for ServiceAccount.scope

---

src/spaceone/identity/model/service_account_model.py
src/spaceone/identity/service/service_account_service.py

feat: modify service_account_type 'TRUST' to 'TRUSTED'

feat: modify service_account_type 'TRUST' to 'TRUSTED'

---

src/spaceone/identity/service/service_account_service.py

fix: modify query filter
fix: add trusted service account type error

fix: modify query filter

---

src/spaceone/identity/service/service_account_service.py

feat: add validation check

---

src/spaceone/identity/conf/provider_conf.py

feat: change aws provider settings

---

src/spaceone/identity/conf/provider_conf.py

fix: fix typo

---

src/spaceone/identity/conf/provider_conf.py

feat: change capability of aws provider

---

src/spaceone/identity/manager/authorization_manager.py

- Add the following authorization scope (`DOAMIN_OR_USER`, `PROJECT_OR_USER`)

feat: add authorization scope

---

src/spaceone/identity/manager/authorization_manager.py

Remove authorization scope
- `DOMAIN_OR_USER`
- `PROJECT_OR_USER`

Rollback Authorization Scope

---

src/spaceone/identity/conf/provider_conf.py

- Change general service account schema of AWS provider
- `aws_assume_role_with_external_id` -> `aws_assume_role`

AWS Provider Schema

---

src/spaceone/identity/manager/service_account_manager.py
src/spaceone/identity/service/service_account_service.py

- fix a bug that the related `TrustedSecret` is not deleted when the trusted service account is deleted

fix: fix trusted secret deletion bug

---

src/spaceone/identity/service/service_account_service.py

- remove secret validation check when deleting service account

refactor: remove validation check

---

.gitignore
skaffold.template.yaml

Signed-off-by: Jongmin Kim <whdalsrnt@megazone.com>
- add skaffold files for developers

build: add skaffold files

---

deploy/helm/templates/_helpers.tpl

- Removed duplicate label from `_helpers.tpl`.

fix: Remove duplicate label

---

src/spaceone/identity/api/v1/user.py
src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/connector/__init__.py
src/spaceone/identity/connector/smtp_connector.py
src/spaceone/identity/error/error_user.py
src/spaceone/identity/manager/__init__.py
src/spaceone/identity/manager/email_manager.py
src/spaceone/identity/manager/token_manager/__init__.py
src/spaceone/identity/manager/token_manager/local_token_manager.py
src/spaceone/identity/manager/user_manager.py
src/spaceone/identity/model/user_model.py
src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/user_service.py
src/spaceone/identity/template/reset_password_link_en.html
src/spaceone/identity/template/verification_code_en.html

- add email send service
- add verify_email and confirm_email 
- modify create 
- add email template
-  #31

Add service for notification email and reset password

---

src/spaceone/identity/service/user_service.py

- fix incorrect method call
- `generate_verify_code` -> `create_verify_code` 
* #31

Fix incorrect method call

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/manager/email_manager.py
src/spaceone/identity/service/user_service.py

- Update global_conf about email config 
* #31

Update global_conf about email config

---

src/setup.py

- addhtml package_data at setup.py
* #31

Add html package_data at setup.py

---

src/spaceone/identity/api/v1/user.py
src/spaceone/identity/info/user_info.py

- modify return value confirm_email
- add email_verified field at user_info.py
* #31

Modify return value confirm_email

---

src/spaceone/identity/service/user_service.py

Exclude reset_password from auth at identity.User service (#31)

---

src/spaceone/identity/service/user_service.py

- Add email_verified check condition when update at identity.User
* #31

Add email_verified check condition when update at identity.User

---

src/spaceone/identity/service/user_service.py

- fix token parameter for get sso url when user create
* #31

Fix token parameter for get sso url when user create

---

src/spaceone/identity/service/user_service.py

- fix get email_verification value at identity.User.update
* #31

Fix get email_verification value at identity.User.update

---

src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/user_service.py

- add email verification code with force value
- remove confirm verify_code from token
- remove using verify_code at issue token 
- get email info from params at identity.user when update 
- fix user update bug  
* #31

Modify update logic of identity.User

---

src/spaceone/identity/service/user_service.py

- Remove deprecated code for email verification
- this code was for auto verification but we decide not to support this function
* #31

Remove deprecated code for email verification

---

src/spaceone/identity/info/user_info.py
src/spaceone/identity/model/user_model.py

Commit for commenting

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/service/user_service.py

- modify token timeout 
- 3600s -> 86400s
* #50

Modify token timeout 

---

src/spaceone/identity/manager/authorization_manager.py
src/spaceone/identity/manager/user_manager.py

* remove trasaction variable used when initializing in manager

Remove trasaction variable used when initializing in manager

---

src/spaceone/identity/connector/auth_plugin_connector.py

…onnector
* Remove trasaction variable used when initializing in AuthPluginConnector

Remove trasaction variable used when initializing in AuthPluginConnector

---

src/spaceone/identity/service/service_account_service.py

- implement `has_secret` option in `ServiceAccount.stat` API

feat: implement has_secret option in ServiceAccount.stat API

---

src/spaceone/identity/conf/permissions_conf.py

- Update default permission for user
- add permission for auth email

Update default permission for user

---

src/spaceone/identity/error/error_user.py

- modify error msg when changed password

Modify error msg when changed password

---

src/spaceone/identity/conf/provider_conf.py

- change azure provider config
- change google provider config

refactor: change provider conf

---

src/spaceone/identity/conf/provider_conf.py

- change azure provider config

refactor: change azure provider conf

---

src/spaceone/identity/connector/smtp_connector.py
src/spaceone/identity/error/error_user.py

- add raise error logic when set smtp sever
* #58

Add raise error logic when set smtp sever

---

src/spaceone/identity/error/error_smtp.py

Add error_smtp.py

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/error/error_mfa.py
src/spaceone/identity/info/authorization_info.py
src/spaceone/identity/info/user_info.py
src/spaceone/identity/interface/grpc/user.py
src/spaceone/identity/manager/email_manager.py
src/spaceone/identity/manager/token_manager/__init__.py
src/spaceone/identity/model/user_model.py
src/spaceone/identity/service/user_service.py

- modify Authorization response message convert method and add apis for mfa
* #64

modify Authorization response message convert method and add apis for mfa

---

deploy/helm/Chart.yaml
src/spaceone/identity/error/error_mfa.py
src/spaceone/identity/manager/token_manager/__init__.py
src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/user_service.py

- add token verification step for mfa enabled user
- upgrade chart version
* #64

Add token verification step for mfa enabled user

---

src/spaceone/identity/info/user_info.py
src/spaceone/identity/model/user_model.py
src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/user_service.py

Remove getattr

---

src/spaceone/identity/info/user_info.py

- add protection code when mfa data is None at user_info
* #64

Add protection code when mfa data is None at user_info

---

src/spaceone/identity/service/token_service.py

- fix None type error when access to uesr info's mfa 
* #64

Fix None type error when access to uesr info's mfa 

---

src/spaceone/identity/manager/token_manager/external_token_manager.py
src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/user_service.py

- extract external user_id
* #64

Extract external user_id

---

src/spaceone/identity/info/user_info.py
src/spaceone/identity/service/token_service.py

- fix external user token issue error
* #64

Fix external user token issue error

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/error/error_mfa.py
src/spaceone/identity/manager/__init__.py
src/spaceone/identity/manager/email_manager.py
src/spaceone/identity/manager/mfa_manager/__init__.py
src/spaceone/identity/manager/mfa_manager/email_mfa_manger.py
src/spaceone/identity/manager/token_manager/__init__.py
src/spaceone/identity/manager/token_manager/external_token_manager.py
src/spaceone/identity/model/user_model.py
src/spaceone/identity/service/user_service.py

Separate mfa manager

---

src/spaceone/identity/manager/mfa_manager/email_mfa_manger.py
src/spaceone/identity/service/token_service.py
src/spaceone/identity/template/authentication_code_en.html
src/spaceone/identity/template/authentication_code_jp.html
src/spaceone/identity/template/authentication_code_ko.html
src/spaceone/identity/template/verification_MFA_code_en.html
src/spaceone/identity/template/verification_MFA_code_jp.html
src/spaceone/identity/template/verification_MFA_code_ko.html

- add templates for mfa through email 
* #64

Add templates for mfa through email 

---

src/spaceone/identity/interface/grpc/domain.py
src/spaceone/identity/manager/domain_manager.py
src/spaceone/identity/model/domain_request.py
src/spaceone/identity/model/domain_response.py
src/spaceone/identity/service/domain_service.py

…tion (#73)
- Add most features exclude user role bindings during domain creation 
- not yet completed -> create, get_metadata, get_public_key
* #73

Add most features exclude user role bindings during domain creation 

---

src/spaceone/identity/service/user_service.py

Fix typo for indent

---

src/spaceone/identity/manager/mfa_manager/email_mfa_manger.py

Fix parameter name

---

src/spaceone/identity/manager/project_manager.py
src/spaceone/identity/manager/user_manager.py
src/spaceone/identity/manager/workspace_manager.py
src/spaceone/identity/model/project/database.py
src/spaceone/identity/model/project/request.py
src/spaceone/identity/model/project/response.py
src/spaceone/identity/model/workspace/database.py
src/spaceone/identity/service/domain_service.py
src/spaceone/identity/service/project_service.py
src/spaceone/identity/service/workspace_service.py

- add workspace service
- add project service
* #73

Add workspace and project  service

---

src/spaceone/identity/service/token_service.py

- fix wrong manager load code
* #73

Fix wrong manager load code

---

src/spaceone/identity/manager/mfa_manager/__init__.py

- modify return value when check mfa verify_code (#64)
* #64

Modify return value when check mfa verify_code

---

src/spaceone/identity/manager/mfa_manager/__init__.py
src/spaceone/identity/manager/mfa_manager/email_mfa_manger.py
src/spaceone/identity/model/token/request.py
src/spaceone/identity/model/user/database.py
src/spaceone/identity/service/domain_service.py
src/spaceone/identity/service/project_group_service.py
src/spaceone/identity/service/project_service.py
src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/user_service.py

- fix init smtp connector
* #73

Fix init smtp connector

---

src/spaceone/identity/manager/domain_secret_manager.py
src/spaceone/identity/manager/user_manager.py

Fix hint type

---

src/spaceone/identity/interface/grpc/__init__.py

Temporary remove api_key service

---

src/spaceone/identity/interface/grpc/__init__.py

Temporary remove auth, and user group service

---

src/spaceone/identity/error/error_project_group.py
src/spaceone/identity/manager/project_group_manager.py
src/spaceone/identity/manager/project_manager.py
src/spaceone/identity/model/project_group/database.py
src/spaceone/identity/model/project_group/request.py
src/spaceone/identity/service/project_group_service.py
src/spaceone/identity/service/project_service.py

- add Project Group service, manager, and model

Add Project Group service, manager, and model

---

src/spaceone/identity/model/role/database.py
src/spaceone/identity/model/role/request.py
src/spaceone/identity/model/role/response.py
src/spaceone/identity/model/user/request.py
src/spaceone/identity/model/user/response.py

- change user model
- change role model

Change User and Role Model

---

src/spaceone/identity/manager/token_manager/__init__.py
src/spaceone/identity/manager/token_manager/local_token_manager.py
src/spaceone/identity/service/token_service.py

Remove check user_type code 

---

src/spaceone/identity/error/error_api_key.py
src/spaceone/identity/interface/grpc/__init__.py
src/spaceone/identity/lib/key_generator.py
src/spaceone/identity/manager/api_key_manager.py
src/spaceone/identity/model/api_key/database.py
src/spaceone/identity/model/api_key/request.py
src/spaceone/identity/model/api_key/response.py
src/spaceone/identity/service/api_key_service.py

- Add create, delete, get, list APIKey apis
* #73

Add create, delete, get, list APIKey apis

---

src/spaceone/identity/manager/api_key_manager.py
src/spaceone/identity/service/api_key_service.py

- Add APIKey apis
- enable, disable, update, stat
* #73

Add APIKey apis

---

src/spaceone/identity/interface/grpc/__init__.py
src/spaceone/identity/model/__init__.py
src/spaceone/identity/model/user/database.py
src/spaceone/identity/model/user/response.py
src/spaceone/identity/model/workspace_user/response.py
src/spaceone/identity/service/domain_service.py
src/spaceone/identity/service/project_service.py
src/spaceone/identity/service/service_account_service.py
src/spaceone/identity/service/workspace_user_service.py

- add `api_key_count` to user model
- add `role_binding_info` to workspace user model
- add `api_key_count` to workspace user model

feat: add api_key_count and role_binding_info field

---

src/spaceone/identity/interface/grpc/__init__.py

fix: fix wrong imports

---

src/spaceone/identity/error/error_project_group.py
src/spaceone/identity/manager/project_group_manager.py
src/spaceone/identity/service/project_group_service.py

- Add check project group sub dir
* #73

Add check project group sub dir

---

src/spaceone/identity/connector/auth_plugin_connector.py
src/spaceone/identity/manager/domain_secret_manager.py
src/spaceone/identity/manager/external_auth_manager.py
src/spaceone/identity/manager/token_manager/external_token_manager.py
src/spaceone/identity/manager/token_manager/local_token_manager.py

- modify external token magaer and external auth apis
* #73

Modify external token magaer and external auth apis

---

src/spaceone/identity/error/error_user_group.py
src/spaceone/identity/interface/grpc/__init__.py
src/spaceone/identity/manager/role_manager.py
src/spaceone/identity/manager/trusted_account_manager.py
src/spaceone/identity/manager/user_group_manager.py
src/spaceone/identity/model/user_group/database.py
src/spaceone/identity/service/app_service.py
src/spaceone/identity/service/domain_service.py
src/spaceone/identity/service/user_group_service.py
src/spaceone/identity/service/user_service.py
src/spaceone/identity/service/workspace_service.py

Add UserGroup apis

---

src/spaceone/identity/service/user_service.py

- add set_required_actions at User service

Add set_required_actions at User service

---

src/spaceone/identity/error/error_user.py
src/spaceone/identity/service/user_service.py

- modify user disable and delete logic when last admin 
* #73

Modify user disable and delete logic when last admin 

---

src/spaceone/identity/lib/key_generator.py
src/spaceone/identity/manager/api_key_manager.py
src/spaceone/identity/manager/token_manager/local_token_manager.py
src/spaceone/identity/service/workspace_service.py

- fix temporary token manager
* #73

Fix temporary token manager

---

src/spaceone/identity/model/user/request.py
src/spaceone/identity/service/user_service.py

- modify keyword field required to optional when user find
* #73

Modify keyword field required to optional when user find

---

src/spaceone/identity/model/app/request.py
src/spaceone/identity/model/role_binding/request.py
src/spaceone/identity/model/trusted_account/request.py
src/spaceone/identity/service/app_service.py
src/spaceone/identity/service/project_service.py
src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/trusted_account_service.py
src/spaceone/identity/service/user_service.py

- apply permission by resource group

feat: apply permission by resource group

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/manager/external_auth_manager.py
src/spaceone/identity/manager/service_account_manager.py
src/spaceone/identity/manager/trusted_account_manager.py

- change the connector load method

refactor: change the connector load method

---

src/spaceone/identity/manager/schema_manager.py
src/spaceone/identity/manager/secret_manager.py
src/spaceone/identity/manager/trusted_account_manager.py
src/spaceone/identity/model/service_account/database.py
src/spaceone/identity/model/service_account/request.py
src/spaceone/identity/model/trusted_account/database.py
src/spaceone/identity/model/trusted_account/request.py
src/spaceone/identity/service/service_account_service.py
src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/trusted_account_service.py

- implement secret management in service account and trusted account
- fix bug when granting token

Implement Secret Management

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/error/error_schema.py
src/spaceone/identity/interface/grpc/workspace.py
src/spaceone/identity/manager/schema_manager.py
src/spaceone/identity/manager/secret_manager.py
src/spaceone/identity/manager/trusted_account_manager.py
src/spaceone/identity/model/app/request.py
src/spaceone/identity/model/project/request.py
src/spaceone/identity/model/project_group/request.py
src/spaceone/identity/model/role_binding/request.py
src/spaceone/identity/model/trusted_account/database.py
src/spaceone/identity/model/user_group/request.py
src/spaceone/identity/model/workspace/request.py
src/spaceone/identity/service/api_key_service.py
src/spaceone/identity/service/app_service.py
src/spaceone/identity/service/external_auth_service.py
src/spaceone/identity/service/project_group_service.py
src/spaceone/identity/service/project_service.py
src/spaceone/identity/service/provider_service.py
src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/role_service.py
src/spaceone/identity/service/schema_service.py
src/spaceone/identity/service/service_account_service.py
src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/trusted_account_service.py
src/spaceone/identity/service/user_group_service.py
src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/user_service.py
src/spaceone/identity/service/workspace_service.py
src/spaceone/identity/service/workspace_user_service.py

feat: change all for SpaceONE 2.0

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/error/error_authentication.py
src/spaceone/identity/error/error_user.py
src/spaceone/identity/service/project_service.py
src/spaceone/identity/service/workspace_service.py

- remove unused error class
- change logic to get created_by value

Refactor Identity

---

src/spaceone/identity/error/error_workspace.py
src/spaceone/identity/manager/mfa_manager/__init__.py
src/spaceone/identity/manager/token_manager/base.py
src/spaceone/identity/manager/workspace_manager.py
src/spaceone/identity/service/token_service.py

- check workspace state when granting token

refactor: check workspace state when granting token

---

src/spaceone/identity/model/token/response.py

- fix no role binding bug in `Token.grant` API

fix: fix no role binding bug in Token.grant API

---

src/spaceone/identity/model/project/request.py
src/spaceone/identity/model/workspace/request.py
src/spaceone/identity/service/project_service.py
src/spaceone/identity/service/workspace_service.py

fix: fix parameter bug

---

src/spaceone/identity/service/user_service.py

Add default language code when create user

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/manager/config_manager.py
src/spaceone/identity/model/domain/response.py
src/spaceone/identity/service/domain_service.py

- add domain config options to Domain.get_auth_info API

feat: add domain config options to Domain.get_auth_info API

---

src/spaceone/identity/service/workspace_user_service.py

- change sort option for compatibility

refactor: change sort option for compatibility

---

src/spaceone/identity/service/role_binding_service.py

fix: fix role type bug

---

pkg/pip_requirements.txt

Change PIP Requirements

---

src/spaceone/identity/manager/service_account_manager.py

fix: fix service account filter

---

src/spaceone/identity/managed_resource/schema/azure_client_secret.yaml
src/spaceone/identity/managed_resource/schema/azure_service_account.yaml
src/spaceone/identity/managed_resource/schema/azure_trusted_account.yaml

- add managed schema for azure

Add managed schema for azure

---

src/spaceone/identity/managed_resource/schema/azure_service_account.yaml

- fix typo in azure_service_account.yaml

Fix typo in azure_service_account.yaml

---

src/spaceone/identity/managed_resource/schema/azure_trusted_account.yaml

- modify related schema at azure_trusted_account.yaml

Modify related schema at azure_trusted_account.yaml

---

src/spaceone/identity/managed_resource/schema/azure_subscription_id.yaml

- add trusting secret schema for azure trusted account

Add trusting secret schema for azure trusted account

---

src/spaceone/identity/service/domain_service.py
src/spaceone/identity/service/system_service.py

- add default user role_type init domain

Add default user role_type init domain

---

src/spaceone/identity/service/domain_service.py
src/spaceone/identity/service/system_service.py

- add role_type for first created domain user

Add role_type for first created domain user

---

src/spaceone/identity/error/error_api_key.py
src/spaceone/identity/error/error_app.py
src/spaceone/identity/interface/grpc/app.py
src/spaceone/identity/lib/key_generator.py
src/spaceone/identity/manager/client_secret_manager.py
src/spaceone/identity/manager/token_manager/grant_token_manager.py
src/spaceone/identity/model/__init__.py
src/spaceone/identity/model/app/database.py
src/spaceone/identity/model/app/request.py
src/spaceone/identity/model/app/response.py
src/spaceone/identity/model/token/request.py
src/spaceone/identity/service/app_service.py

refactor: refactor fields in app

---

src/spaceone/identity/manager/token_manager/__init__.py

- add import external token manager

Add import external token manager

---

src/spaceone/identity/manager/token_manager/external_token_manager.py

- fix external manager instance error

Fix external manager instance error

---

src/spaceone/identity/service/workspace_user_service.py

- Add accessible role_type for WorkspaceUser get, list api

Add accessible role_type for WorkspaceUser get, list api

---

src/spaceone/identity/interface/grpc/workspace_user.py
src/spaceone/identity/manager/workspace_user_manager.py
src/spaceone/identity/service/workspace_user_service.py

- fix bugs in WorkspaceUser.stat API

fix: fix bugs in WorkspaceUser.stat API

---

src/spaceone/identity/service/workspace_user_service.py

fix: fix permission bug

---

src/spaceone/identity/manager/token_manager/external_token_manager.py

- fix update external user state error

Fix update external user state error

---

src/spaceone/identity/model/app/database.py
src/spaceone/identity/model/app/response.py
src/spaceone/identity/service/app_service.py

Add last_access_at data for App

---

.gitignore
src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/manager/token_manager/base.py

- modify default token expired time

Modify default token expired time

---

src/spaceone/identity/model/user/database.py
src/spaceone/identity/model/user/response.py
src/spaceone/identity/service/role_binding_service.py

Add role_id at UserResponse

---

src/spaceone/identity/service/app_service.py

- fix last_accessed_at target vo

Fix last_accessed_at target vo

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/manager/token_manager/base.py

- modify default timeout seconds for token

Modify default timeout seconds for token

---

src/spaceone/identity/managed_resource/schema/azure_secret_client_secret.yaml
src/spaceone/identity/managed_resource/schema/azure_secret_subscription_id.yaml
src/spaceone/identity/managed_resource/schema/google_secret_oauth2_credentials.yaml
src/spaceone/identity/managed_resource/schema/google_secret_project_id.yaml
src/spaceone/identity/manager/workspace_manager.py
src/spaceone/identity/service/workspace_service.py
src/spaceone/identity/service/workspace_user_service.py

- add cascade delete role bindings with workspace
- add DOMAIN_ADMIN role_type for WorkspaceUser
- edit managed_resource schema

Add cascade delete role bindings with workspace

---

src/spaceone/identity/service/user_profile_service.py

- remove `DISABLED` workspaces in UserProfile.get_workspaces API

refactor: remove DISABLED workspaces in UserProfile.get_workspaces API

---

src/spaceone/identity/service/workspace_user_service.py

- fix wrong query in WorkspaceUser.list API

fix: fix wrong query in WorkspaceUser.list API

---

src/spaceone/identity/managed_resource/schema/google_cloud_service_account.yaml
src/spaceone/identity/managed_resource/schema/google_cloud_trusted_account.yaml
src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/workspace_user_service.py
src/spaceone/identity/template/reset_pwd_link_when_user_added_en.html
src/spaceone/identity/template/reset_pwd_link_when_user_added_ja.html
src/spaceone/identity/template/reset_pwd_link_when_user_added_ko.html

-modify reset_pwd_link_when_user_added.html email template
- modify google managed_service_account resource helper description

Modify reset_pwd_link_when_user_added.html email template

---

src/spaceone/identity/error/error_role.py
src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/user_service.py

- check last admin and workspace owner when modify role binding

Check last admin and workspace owner when modify role binding

---

src/spaceone/identity/service/role_binding_service.py

- fix typo when get enabled user state

Fix typo when get enabled user state

---

src/spaceone/identity/service/role_binding_service.py

- fix role update rule based on DOMAIN ADMIN

Fix role update rule based on DOMAIN ADMIN

---

pkg/pip_requirements.txt
src/setup.py

build: change require packages

---

src/spaceone/identity/model/workspace/database.py
src/spaceone/identity/service/workspace_service.py

fix: fix unique field bug

---

src/spaceone/identity/model/trusted_account/request.py

fix: change require fields

---

src/spaceone/identity/service/app_service.py
src/spaceone/identity/service/domain_service.py
src/spaceone/identity/service/system_service.py
src/spaceone/identity/service/workspace_service.py

- apply internal authentication

feat: apply internal authentication

---

src/spaceone/identity/service/domain_service.py
src/spaceone/identity/service/system_service.py

refactor: change error message

---

src/spaceone/identity/manager/mfa_manager/base.py
src/spaceone/identity/manager/mfa_manager/email_mfa_manger.py
src/spaceone/identity/manager/token_manager/__init__.py
src/spaceone/identity/manager/token_manager/base.py
src/spaceone/identity/manager/token_manager/external_token_manager.py
src/spaceone/identity/manager/token_manager/local_token_manager.py
src/spaceone/identity/manager/token_manager/mfa_token_manager.py
src/spaceone/identity/model/token/request.py
src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/user_profile_service.py

Add mfa token manager

---

src/spaceone/identity/connector/smtp_connector.py
src/spaceone/identity/manager/email_manager.py
src/spaceone/identity/service/domain_service.py
src/spaceone/identity/service/system_service.py

Add email send function when domain created

---

src/spaceone/identity/manager/mfa_manager/base.py
src/spaceone/identity/manager/mfa_manager/email_mfa_manger.py
src/spaceone/identity/service/token_service.py

Fix external auth mfa verification

---

src/spaceone/identity/manager/mfa_manager/base.py

Fix dictionary ordering for hashing

---

src/spaceone/identity/manager/mfa_manager/base.py

Add debug code

---

src/spaceone/identity/manager/token_manager/external_token_manager.py

Remove user info at credentials

---

src/spaceone/identity/lib/key_generator.py
src/spaceone/identity/manager/mfa_manager/base.py
src/spaceone/identity/manager/token_manager/mfa_token_manager.py

Remove debug code

---

src/spaceone/identity/manager/external_auth_manager.py
src/spaceone/identity/manager/secret_manager.py

fix: change wrong system token

---

src/spaceone/identity/service/domain_service.py
src/spaceone/identity/service/system_service.py

- add role_id when domain created

Add role_id when domain created

---

src/spaceone/identity/service/user_service.py

- fix last admin delete condition

Fix last admin delete condition

---

src/spaceone/identity/managed_resource/schema/azure_service_account.yaml
src/spaceone/identity/managed_resource/schema/azure_trusted_account.yaml
src/spaceone/identity/managed_resource/schema/google_cloud_service_account.yaml
src/spaceone/identity/managed_resource/schema/google_cloud_trusted_account.yaml

- Update google, azure service account schema version

Update google, azure service account schema version

---

src/spaceone/identity/manager/mfa_manager/base.py
src/spaceone/identity/manager/token_manager/mfa_token_manager.py

- fix mfa authentication check error

Fix mfa authentication check error

---

src/spaceone/identity/model/project/request.py
src/spaceone/identity/model/workspace/request.py
src/spaceone/identity/service/project_service.py

- add `include_children` option to Project.list API

feat: add include_children option to Project.list API

---

src/spaceone/identity/manager/external_auth_manager.py
src/spaceone/identity/manager/secret_manager.py
src/spaceone/identity/model/domain/request.py
src/spaceone/identity/model/project/request.py
src/spaceone/identity/model/workspace/request.py
src/spaceone/identity/service/project_service.py

Add reset_password field at Admin User

Add reset_password field at Admin User 

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/service/user_service.py

- Extend timeout for invited user

Extend timeout for invited user

---

src/spaceone/identity/service/role_binding_service.py

Role binding delete error with role_id

---

src/spaceone/identity/manager/mfa_manager/base.py
src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/user_service.py

Fix get token timeout

---

src/spaceone/identity/manager/token_manager/base.py
src/spaceone/identity/model/token/request.py
src/spaceone/identity/service/token_service.py

Modify token grant api for temporary token

---

src/spaceone/identity/service/token_service.py

Modify token grant permissions for temporary token

---

src/spaceone/identity/manager/workspace_user_manager.py
src/spaceone/identity/model/workspace_user/request.py
src/spaceone/identity/service/workspace_user_service.py

Add role_type for workspace user api

---

src/spaceone/identity/service/role_binding_service.py

- fix update role binding error with 'WORKSPACE' role_id

Fix update role binding error with 'WORKSPACE' role_id

---

src/spaceone/identity/manager/schema_manager.py
src/spaceone/identity/model/schema/request.py
src/spaceone/identity/service/schema_service.py

Fix update schema error

---

src/spaceone/identity/managed_resource/provider/azure.yaml
src/spaceone/identity/plugin/account_collector/conf/global_conf.py
src/spaceone/identity/plugin/account_collector/interface/grpc/__init__.py
src/spaceone/identity/plugin/account_collector/interface/grpc/account_collector.py
src/spaceone/identity/plugin/account_collector/lib/server.py
src/spaceone/identity/plugin/account_collector/model/account_collect_request.py
src/spaceone/identity/plugin/account_collector/model/account_collect_response.py
src/spaceone/identity/plugin/account_collector/service/account_collector_service.py
src/spaceone/identity/plugin/account_collector/skeleton/main.py

- add plugin interface and skeleton code
* #199

Add plugin interface and skeleton code

---

src/spaceone/identity/model/trusted_account/response.py

- fix typo at trusted account response

Fix typo at trusted account response

---

deploy/helm/Chart.yaml
deploy/helm/values.yaml
src/spaceone/identity/connector/account_collector_plugin_connector.py
src/spaceone/identity/error/error_job.py
src/spaceone/identity/interface/grpc/provider.py
src/spaceone/identity/interface/task/v1/trusted_account_sync_scheduler.py
src/spaceone/identity/manager/account_collector_plugin_manager.py
src/spaceone/identity/manager/job_manager.py
src/spaceone/identity/manager/plugin_manager.py
src/spaceone/identity/model/job/database.py
src/spaceone/identity/model/job/request.py
src/spaceone/identity/model/job/response.py
src/spaceone/identity/model/provider/request.py
src/spaceone/identity/model/provider/response.py
src/spaceone/identity/model/trusted_account/request.py
src/spaceone/identity/service/job_service.py
src/spaceone/identity/service/provider_service.py
src/spaceone/identity/service/trusted_account_service.py

- add job service
- add trusted account sync service
- add scheduler interface
- update helm chart values and version
* #199

Add services and scheduler 

---

src/spaceone/identity/conf/global_conf.py

- udate global config for QUEUES settings
* #199

Udate global config for QUEUES settings

---

src/spaceone/identity/manager/job_manager.py
src/spaceone/identity/model/job/database.py
src/spaceone/identity/model/job/response.py
src/spaceone/identity/service/job_service.py
src/spaceone/identity/service/trusted_account_service.py

- Fix job_id prefix 'pg' to 'job'
* #199

Fix job_id prefix 'pg' to 'job'

---

src/spaceone/identity/interface/task/v1/trusted_account_sync_scheduler.py
src/spaceone/identity/manager/job_manager.py
src/spaceone/identity/model/job/database.py
src/spaceone/identity/model/job/response.py
src/spaceone/identity/service/job_service.py

- modify scheduler sync parameter
Because of this, currently scheduler doesn't work.
* #199

Modify scheduler sync parameter

---

src/spaceone/identity/manager/__init__.py
src/spaceone/identity/manager/job_manager.py
src/spaceone/identity/service/job_service.py

- add trusted account sync api

Add trusted account sync api

---

src/spaceone/identity/interface/task/v1/trusted_account_sync_scheduler.py
src/spaceone/identity/manager/secret_manager.py
src/spaceone/identity/service/__init__.py
src/spaceone/identity/service/job_service.py

- add trusted secret get data at secret manager 
- modify scheduler sync hour condition

Add trusted secret get data at secret manager 

---

src/spaceone/identity/interface/grpc/project_group.py
src/spaceone/identity/manager/job_manager.py
src/spaceone/identity/model/project_group/database.py
src/spaceone/identity/model/project_group/request.py
src/spaceone/identity/model/project_group/response.py
src/spaceone/identity/service/job_service.py
src/spaceone/identity/service/project_group_service.py

- add api for user add and remove at ProjectGroup (#210)
- modify get secret type 'secret' -> 'trusted_secret' ( #199)

Add api for user add and remove at ProjectGroup

---

src/spaceone/identity/interface/grpc/role.py
src/spaceone/identity/manager/role_manager.py
src/spaceone/identity/model/role/database.py
src/spaceone/identity/model/role/request.py
src/spaceone/identity/model/role/response.py
src/spaceone/identity/service/role_service.py

- add 'state' field for Role and apis 'enable', 'disable'

Add 'state' field for Role and apis 'enable', 'disable'

---

src/spaceone/identity/manager/project_group_manager.py
src/spaceone/identity/service/token_service.py

- add users projects in project group when grant token (#210)
* #210

Add users projects in project group when grant token

---

src/spaceone/identity/connector/account_collector_plugin_connector.py
src/spaceone/identity/manager/account_collector_plugin_manager.py
src/spaceone/identity/manager/job_manager.py
src/spaceone/identity/service/job_service.py
src/spaceone/identity/service/provider_service.py

- add create project_group and workspace when sync trusted account
* #199

Add create project_group and workspace when sync trusted account

---

src/spaceone/identity/error/error_project_group.py
src/spaceone/identity/manager/project_group_manager.py
src/spaceone/identity/service/project_group_service.py

- add permission for workspace_member for user add and remove (#199)

Add permission for workspace_member for user add and remove

---

src/spaceone/identity/interface/grpc/trusted_account.py
src/spaceone/identity/model/job/database.py
src/spaceone/identity/model/job/response.py
src/spaceone/identity/service/job_service.py

- fix response message at ta sync api
* #199

fix response message at ta sync api

---

src/spaceone/identity/model/project/database.py
src/spaceone/identity/model/project/response.py
src/spaceone/identity/model/project_group/database.py
src/spaceone/identity/model/project_group/response.py
src/spaceone/identity/model/service_account/database.py
src/spaceone/identity/model/service_account/response.py
src/spaceone/identity/model/workspace/response.py
src/spaceone/identity/service/job_service.py

- modify sa, project, project_group, workspace response model
* #199

Modify sa, project, project_group, workspace response model

---

src/spaceone/identity/manager/job_manager.py
src/spaceone/identity/service/job_service.py

Add job error message 

---

src/spaceone/identity/service/job_service.py

Fix to_dict error when account sync (#199)

---

src/spaceone/identity/manager/secret_manager.py
src/spaceone/identity/service/job_service.py

- fix get secret_data method
* #199

Fix get secret_data method

---

src/spaceone/identity/plugin/account_collector/model/account_collect_response.py
src/spaceone/identity/plugin/account_collector/skeleton/main.py
src/spaceone/identity/service/job_service.py

- modify identity plugin skeleton code

Modify identity plugin skeleton code

---

src/spaceone/identity/service/job_service.py

- Fix parameter field when create project

Fix parameter field when create project

---

src/spaceone/identity/error/custom.py
src/spaceone/identity/manager/job_manager.py
src/spaceone/identity/manager/resource_manager.py
src/spaceone/identity/manager/secret_manager.py
src/spaceone/identity/manager/service_account_manager.py
src/spaceone/identity/service/job_service.py
src/spaceone/identity/service/project_group_service.py
src/spaceone/identity/service/project_service.py
src/spaceone/identity/service/service_account_service.py
src/spaceone/identity/service/workspace_service.py

- add managed resource modify rule

Add managed resource modify rule

---

src/spaceone/identity/interface/grpc/user_profile.py
src/spaceone/identity/model/user_profile/response.py
src/spaceone/identity/service/user_profile_service.py

- modify get-workspace api response

Modify get-workspace api response

---

src/spaceone/identity/manager/job_manager.py
src/spaceone/identity/model/job/database.py
src/spaceone/identity/model/job/response.py
src/spaceone/identity/model/trusted_account/database.py
src/spaceone/identity/model/trusted_account/request.py
src/spaceone/identity/model/trusted_account/response.py
src/spaceone/identity/service/job_service.py
src/spaceone/identity/service/trusted_account_service.py

- add plugin_options for trusted_account
* #199

Add plugin_options for trusted_account

---

src/spaceone/identity/model/provider/response.py

- add metadata field at provider plugin_info
* #199

Add metadata field at provider plugin_info 

---

src/spaceone/identity/manager/job_manager.py
src/spaceone/identity/model/workspace/database.py
src/spaceone/identity/service/job_service.py

- add is_managed field at Workspace model 
- change job status error
* #199

Add is_managed field at Workspace model 

---

src/spaceone/identity/model/user_profile/response.py
src/spaceone/identity/service/user_profile_service.py

- add role_name at MyWorkspaceInfo

Add role_name at MyWorkspaceInfo

---

src/spaceone/identity/manager/secret_manager.py
src/spaceone/identity/service/job_service.py

- modify delete_secrete at secret manager

Modify delete_secrete at secret manager

---

src/spaceone/identity/service/job_service.py
src/spaceone/identity/service/user_profile_service.py

- add skip condition when try to save duplicated resource

Add skip condition when try to save duplicated resource

---

src/spaceone/identity/model/job/database.py

- modify updatable_fields at Job model
* #199

Modify updatable_fields at Job model

---

src/spaceone/identity/model/service_account/database.py

- modify unique rule for service account name
* #199

Modify unique rule for service account name

---

src/spaceone/identity/managed_resource/provider/google_cloud.yaml

* Add plugin_id in google_cloud yaml file

Add plugin_id in google_cloud yaml file

---

src/spaceone/identity/manager/job_manager.py
src/spaceone/identity/manager/resource_manager.py
src/spaceone/identity/model/project/database.py
src/spaceone/identity/model/project/response.py
src/spaceone/identity/model/project_group/database.py
src/spaceone/identity/model/project_group/response.py
src/spaceone/identity/model/workspace/database.py
src/spaceone/identity/model/workspace/response.py
src/spaceone/identity/service/job_service.py

- add insert trusted account id logic at auto synced resource
* #199

Add insert trusted account id logic at auto synced resource

---

src/spaceone/identity/managed_resource/provider/google_cloud.yaml

- update google cloud provider at managed_resource

Update google cloud provider at managed_resource

---

src/spaceone/identity/error/custom.py
src/spaceone/identity/manager/resource_manager.py
src/spaceone/identity/model/service_account/database.py

- fix managed resource by auto sync delete condition
* #199

fix managed resource by auto sync delete condition

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/error/custom.py

Modify error message from custom error

---

src/spaceone/identity/managed_resource/provider/aws.yaml
src/spaceone/identity/managed_resource/schema/azure_secret_multi_tenant.yaml
src/spaceone/identity/managed_resource/schema/azure_service_account.yaml
src/spaceone/identity/manager/schema_manager.py
src/spaceone/identity/service/job_service.py

- update managed provider version (aws)
- #199

Update managed provider version (aws)

---

deploy/helm/Chart.yaml
deploy/helm/config/config.yaml

- update helm chart version 1.3.14
* #199

Update helm chart version 1.3.14

---

src/spaceone/identity/service/job_service.py

- Fix get workspace parameter order error
* #199

Fix get workspace parameter order error

---

src/spaceone/identity/managed_resource/schema/aws_control_tower_schema.yaml
src/spaceone/identity/managed_resource/schema/aws_security_ou_schema.yaml
src/spaceone/identity/managed_resource/schema/aws_trusted_account.yaml

Added 2 new schemas needed for aws account sync function

---

src/spaceone/identity/managed_resource/schema/aws_control_tower_schema.yaml
src/spaceone/identity/managed_resource/schema/aws_security_ou_schema.yaml

Added version to each new schema

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/model/job/request.py
src/spaceone/identity/service/job_service.py

- add permission for WORKSPACE MEMBER when job read 
- add random workspace color
* #199

Add permission for WORKSPACE MEMBER when job read 

---

src/spaceone/identity/service/job_service.py

- Add trusted_account_id at managed workspace
* #199

Add trusted_account_id at managed workspace

---

src/spaceone/identity/model/job/response.py
src/spaceone/identity/model/project_group/database.py

- fix job status typo error
- *#199

Fix job status typo error

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/service/job_service.py

- Add duplicated workspace create logic

Add duplicated workspace create logic

---

src/spaceone/identity/model/agent/response.py
src/spaceone/identity/service/agent_service.py

Merge agent_info with app_info

Merge agent_info with app_info

---

src/spaceone/identity/managed_resource/provider/google_cloud.yaml

* Modify yaml file of google cloud settings

Modify yaml file of google cloud settings

---

src/spaceone/identity/service/job_service.py

Modify debug code

---

src/spaceone/identity/service/agent_service.py

Add Agent list query 

---

src/spaceone/identity/managed_resource/provider/google_cloud.yaml
src/spaceone/identity/model/workspace/request.py
src/spaceone/identity/service/agent_service.py
src/spaceone/identity/service/job_service.py
src/spaceone/identity/service/service_account_service.py
src/spaceone/identity/service/trusted_account_service.py
src/spaceone/identity/service/workspace_service.py

Add delete workspace related resource with identity

---

src/spaceone/identity/service/workspace_service.py

Modify error msg

---

src/spaceone/identity/error/custom.py
src/spaceone/identity/manager/resource_manager.py
src/spaceone/identity/service/project_group_service.py
src/spaceone/identity/service/project_service.py
src/spaceone/identity/service/service_account_service.py
src/spaceone/identity/service/workspace_service.py

Modify error code 

---

src/spaceone/identity/service/job_service.py

- Fix create workspace error when skip project group
* #199

Fix create workspace error when skip project group

---

src/spaceone/identity/service/job_service.py

- Fix update project and project group logic
* #199

Fix update project and project group logic

---

src/spaceone/identity/model/project/database.py
src/spaceone/identity/model/project_group/database.py

- Modify max length of project and project group name

Modify max length of project and project group name

---

src/spaceone/identity/managed_resource/provider/kubernetes.yaml
src/spaceone/identity/managed_resource/schema/kubernetes_service_account.yaml

I have added the corresponding YAML spec as Kubernetes becomes a managed resource.

Add managed resource and schema of k8s

---

src/spaceone/identity/model/project/database.py

- fix max length of project name

Fix max length of project name

---

src/spaceone/identity/model/workspace/database.py
src/spaceone/identity/model/workspace/response.py
src/spaceone/identity/service/job_service.py

- modify field 'reference_id' -> 'references' at WorkspaceInfo
* #199

Modify field 'reference_id' -> 'references' at WorkspaceInfo

---

src/spaceone/identity/service/job_service.py

- None type error when check workspace references value
* #199

None type error when check workspace references value

---

src/spaceone/identity/managed_resource/provider/aws.yaml
src/spaceone/identity/managed_resource/schema/aws_control_tower_schema.yaml

Updated schemas related to control tower

---

src/spaceone/identity/service/job_service.py

- fix the error of not saving references

Fix the error of not saving references

---

src/spaceone/identity/service/agent_service.py

Modify role types to Agent get, list

Modify role types to Agent get, list

---

src/spaceone/identity/error/error_authentication.py
src/spaceone/identity/service/token_service.py

- Add check required actions when grant token

Add check required actions when grant token

---

src/spaceone/identity/service/agent_service.py

Add DOMAIN_ADMIN role type to Agent get, list

Add DOMAIN_ADMIN role type to Agent get, list

---

src/spaceone/identity/plugin/external_auth/conf/global_conf.py
src/spaceone/identity/plugin/external_auth/interface/grpc/__init__.py
src/spaceone/identity/plugin/external_auth/interface/grpc/external_auth.py
src/spaceone/identity/plugin/external_auth/lib/server.py
src/spaceone/identity/plugin/external_auth/model/external_auth_request.py
src/spaceone/identity/plugin/external_auth/model/external_auth_response.py
src/spaceone/identity/plugin/external_auth/service/external_auth_service.py
src/spaceone/identity/plugin/external_auth/skeleton/main.py

Add external_auth skeleton code

Add external_auth skeleton code

---

src/spaceone/identity/service/user_service.py

- Modify user_id uses after user create

Modify user_id uses after user create 

---

src/spaceone/identity/plugin/external_auth/service/external_auth_service.py

Fix wrong import of UserResponse

Fix wrong import of UserResponse

---

src/spaceone/identity/plugin/external_auth/model/external_auth_response.py

Change variable group_id to group of UserResponse

Change variable group_id to group of UserResponse

---

src/spaceone/identity/service/service_account_service.py

- modify service account limit '1000' -> '2000'

Modify service account limit '1000' -> '2000'

---

src/spaceone/identity/model/user/database.py

Modify 'user_id' max length 40->60

---

src/spaceone/identity/connector/smtp_connector.py
src/spaceone/identity/manager/token_manager/base.py
src/spaceone/identity/manager/workspace_user_manager.py
src/spaceone/identity/plugin/external_auth/model/external_auth_response.py
src/spaceone/identity/plugin/external_auth/service/external_auth_service.py
src/spaceone/identity/service/user_service.py

- fix issue when admin role_id was added when creating workspace use

Fix issue when admin role_id was added when creating workspace use

---

src/spaceone/identity/error/error_external_auth.py
src/spaceone/identity/service/external_auth_service.py

Add edge case for required fields

Add edge case for required fields

---

src/spaceone/identity/service/token_service.py

- fix default role type when grant token

Fix default role type when grant token

---

src/spaceone/identity/service/user_service.py
src/spaceone/identity/template/reset_pwd_link_when_pw_forgotten_en.html
src/spaceone/identity/template/reset_pwd_link_when_user_added_en.html

- add default timezone when create user 
- fix typo at template 'resset' -> 'reset'

Add default timezone when create user 

---

src/spaceone/identity/manager/email_manager.py
src/spaceone/identity/model/user/request.py
src/spaceone/identity/model/workspace_user/response.py

- add email_verified field at WorkspaceUser response

Add email_verified field at WorkspaceUser response

---

src/spaceone/identity/error/error_user.py
src/spaceone/identity/manager/user_manager.py

- add email verify method at user_manager

Add email verify method at user_manager

---

deploy/helm/Chart.yaml
deploy/helm/values.yaml
src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/interface/task/v1/dormancy_scheduler.py
src/spaceone/identity/manager/cost_analysis_manager.py
src/spaceone/identity/manager/job_manager.py
src/spaceone/identity/manager/service_account_manager.py
src/spaceone/identity/service/job_service.py

- implement dormancy features
- add dormancy scheduler to helm chart

Implement Dormancy Features

---

src/spaceone/identity/manager/user_manager.py
src/spaceone/identity/service/system_service.py

- remove user_id format validation logic for LOCAL type user

Remove user_id format validation logic for LOCAL type user

---

src/spaceone/identity/connector/account_collector_plugin_connector.py
src/spaceone/identity/error/error_project.py
src/spaceone/identity/manager/account_collector_plugin_manager.py
src/spaceone/identity/manager/endpoint_manager.py
src/spaceone/identity/manager/managed_resource_manager.py
src/spaceone/identity/manager/mfa_manager/base.py
src/spaceone/identity/manager/mfa_manager/email_mfa_manger.py
src/spaceone/identity/manager/project_group_manager.py
src/spaceone/identity/manager/provider_manager.py
src/spaceone/identity/manager/role_binding_manager.py
src/spaceone/identity/manager/token_manager/external_token_manager.py
src/spaceone/identity/model/domain/database.py
src/spaceone/identity/model/external_auth/database.py
src/spaceone/identity/model/schema/database.py
src/spaceone/identity/model/schema/request.py
src/spaceone/identity/model/schema/response.py
src/spaceone/identity/service/app_service.py
src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/service_account_service.py
src/spaceone/identity/service/workspace_user_service.py

Apply black code formatter

---

src/spaceone/identity/manager/secret_manager.py
src/spaceone/identity/service/job_service.py

- modify update secret logic when service account auto sync

Modify update secret logic when service account auto sync

---

src/spaceone/identity/manager/secret_manager.py
src/spaceone/identity/service/job_service.py

- fix list secrets method at secret manager 
- update last_synced at when service account sync

Fix list secrets method at secret manager 

---

src/spaceone/identity/model/app/database.py
src/spaceone/identity/model/app/request.py
src/spaceone/identity/model/app/response.py
src/spaceone/identity/service/app_service.py
src/spaceone/identity/service/user_service.py

- Add new feature for App Service with 'Workspace Member' role

Add new feature for App Service with 'Workspace Member' role

---

.gitignore
src/spaceone/identity/error/custom.py
src/spaceone/identity/interface/grpc/__init__.py
src/spaceone/identity/interface/grpc/workspace_group.py
src/spaceone/identity/manager/user_manager.py
src/spaceone/identity/manager/workspace_group_manager.py
src/spaceone/identity/model/role_binding/database.py
src/spaceone/identity/model/role_binding/response.py
src/spaceone/identity/model/workspace_group/database.py
src/spaceone/identity/model/workspace_group/request.py
src/spaceone/identity/model/workspace_group/response.py
src/spaceone/identity/model/workspace_user/response.py
src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/workspace_group_service.py
src/spaceone/identity/service/workspace_service.py

I have added a new feature for Workspace Group and implemented the logic to create the related Role Binding.

Add workspace group feature

---

src/spaceone/identity/model/workspace_group/request.py
src/spaceone/identity/service/workspace_group_service.py

Add docstring

---

src/spaceone/identity/interface/grpc/__init__.py
src/spaceone/identity/interface/grpc/workspace_group_details.py
src/spaceone/identity/model/workspace_group_details/database.py
src/spaceone/identity/model/workspace_group_details/request.py
src/spaceone/identity/model/workspace_group_details/response.py
src/spaceone/identity/service/workspace_group_details_service.py

Add workspace group details prototype

Add workspace group details prototype

---

Dockerfile

Modify python-core version because of protobuf issue

Modify python-core version because of protobuf issue

---

pkg/pip_requirements.txt

Modify pip_requirements because of protobuf issue

Modify pip_requirements because of protobuf issue

---

pkg/pip_requirements.txt

Modify protobuf version because of protobuf issue

Modify protobuf version because of protobuf issue

---

Dockerfile
pkg/pip_requirements.txt

Upgrade protobuf version because of protobuf issue

Upgrade protobuf version because of protobuf issue

---

Dockerfile

- temporary comment upgrade protobuf command at DockerfileX

Temporary comment upgrade protobuf command at Dockerfile

---

Dockerfile
src/spaceone/identity/model/workspace_group_details/request.py
src/spaceone/identity/service/workspace_group_details_service.py

Add user_id which is injected from auth

Add user_id which is injected from auth

---

src/spaceone/identity/model/workspace_group/database.py
src/spaceone/identity/model/workspace_group/request.py
src/spaceone/identity/model/workspace_group/response.py
src/spaceone/identity/service/workspace_group_service.py

Modify user type to list of dictionary

Modify user type to list of dictionary

---

src/spaceone/identity/error/error_role.py
src/spaceone/identity/interface/grpc/workspace_group.py
src/spaceone/identity/model/workspace_group/request.py
src/spaceone/identity/model/workspace_group/response.py
src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/workspace_group_service.py

Add update_role method and delete role_binding when remove workspaces&users

Add update_role method and delete role_binding when remove workspaces&users

---

.gitignore
src/spaceone/identity/error/custom.py
src/spaceone/identity/manager/workspace_group_user_manager.py
src/spaceone/identity/model/workspace_group_user/request.py
src/spaceone/identity/service/workspace_group_service.py
src/spaceone/identity/service/workspace_group_user_service.py

Fix the bug and add find, get, list, and stat methods in WorkspaceGroupUser

Fix the bug and add find, get, list, and stat methods in WorkspaceGroupUser

---

src/spaceone/identity/service/workspace_group_service.py

Modify code when there are no workspace users

Modify code when there are no workspace users

---

src/spaceone/identity/manager/workspace_group_manager.py
src/spaceone/identity/manager/workspace_group_user_manager.py
src/spaceone/identity/model/workspace_group_user/request.py
src/spaceone/identity/service/workspace_group_user_service.py

Add add, remove, update_role methods

Add add, remove, update_role methods

---

src/spaceone/identity/model/workspace_group_user/request.py
src/spaceone/identity/service/workspace_group_user_service.py

Change variable name

---

src/spaceone/identity/service/workspace_group_service.py
src/spaceone/identity/service/workspace_group_user_service.py

Remove role_id when update the role

Remove role_id when update the role

---

src/spaceone/identity/manager/workspace_group_user_manager.py
src/spaceone/identity/manager/workspace_manager.py
src/spaceone/identity/model/role_binding/database.py
src/spaceone/identity/model/workspace/database.py
src/spaceone/identity/model/workspace/response.py
src/spaceone/identity/service/role_binding_service.py

Add user_count to workspace

---

src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/workspace_service.py

Modify workspace member access to get_workspace_groups api

Modify workspace member access to get_workspace_groups api

---

src/spaceone/identity/service/role_binding_service.py

Modify role binding code when workspace_vo exist

Modify role binding code when workspace_vo exist

---

src/spaceone/identity/error/custom.py

Add custom errors

---

src/spaceone/identity/model/workspace/database.py

Add worksapce_group_id to the workspace database

Add worksapce_group_id to the workspace database

---

src/spaceone/identity/manager/role_binding_manager.py

- add delete rolebinding debug code

Add delete rolebinding debug code

---

src/spaceone/identity/manager/workspace_user_manager.py
src/spaceone/identity/model/workspace_user/response.py

Rollback role_binding_info to the dictionary in the workspace user

Rollback role_binding_info to the dictionary in the workspace user

---

src/spaceone/identity/service/workspace_service.py

Modify parameter

---

src/spaceone/identity/manager/workspace_group_user_manager.py
src/spaceone/identity/model/workspace_group_user/response.py
src/spaceone/identity/service/workspace_group_service.py
src/spaceone/identity/service/workspace_group_user_service.py

Modify WorkspaceGroupUser APIs

Modify WorkspaceGroupUser APIs

---

src/spaceone/identity/model/user_profile/response.py
src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/workspace_group_service.py

Update get_workspace_groups API of UserProfile

Update get_workspace_groups API of UserProfile

---

src/spaceone/identity/service/workspace_group_service.py

Add user_name and state when get the WorkspaceGroup

Add user_name and state when get the WorkspaceGroup

---

src/spaceone/identity/service/workspace_group_service.py

Add user_name and state when listing the WorkspaceGroup

Add user_name and state when listing the WorkspaceGroup

---

src/spaceone/identity/manager/workspace_group_user_manager.py
src/spaceone/identity/model/workspace_group_user/response.py
src/spaceone/identity/service/workspace_group_service.py
src/spaceone/identity/service/workspace_group_user_service.py

Refactor the code and update workspace group user

Refactor the code and update workspace group user

---

src/spaceone/identity/service/workspace_group_service.py
src/spaceone/identity/service/workspace_group_user_service.py

Modify code when there are no users in the WorkspaceGroup

Modify code when there are no users in the WorkspaceGroup

---

src/spaceone/identity/service/workspace_group_service.py

Modify code to get audience, not user_id

Modify code to get audience, not user_id

---

src/spaceone/identity/model/workspace_group_user/response.py
src/spaceone/identity/service/workspace_group_user_service.py

Refactor code such that unify workspace group user response

Refactor code such that unify workspace group user response

---

src/spaceone/identity/interface/grpc/workspace_group_user.py

Update to ParseDict from dict_to_message

Update to ParseDict from dict_to_message

---

src/spaceone/identity/manager/user_manager.py
src/spaceone/identity/service/user_profile_service.py

Modify code such that when deleting the user and adding the `workspace_group_id` filter

Modify code such that when deleting the user and adding the `workspace_group_id` filter

---

src/spaceone/identity/service/workspace_group_service.py

Add unique user_id to workspace group although the user has workspaces

Add unique user_id to workspace group although the user has workspaces

---

src/spaceone/identity/service/workspace_service.py

Remove workspaces field of workspace_group_info

Remove workspaces field of workspace_group_info

---

src/spaceone/identity/model/token/response.py
src/spaceone/identity/model/workspace/database.py
src/spaceone/identity/service/token_service.py

-remove logic for creating combined-role

Remove logic for creating combined-role

---

src/spaceone/identity/service/workspace_service.py

Modify code when changing workspace's workspace group

Modify code when changing workspace's workspace group

---

src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/workspace_group_service.py
src/spaceone/identity/service/workspace_group_user_service.py

Modify code when adding users to the workspace group

Modify code when adding users to the workspace group

---

src/spaceone/identity/service/workspace_group_service.py

Update workspace user_count when remove a user from a workspac_group

Update workspace user_count when remove a user from a workspac_group

---

src/spaceone/identity/service/workspace_group_service.py

Modify params code when workspace_id is None

Modify params code when workspace_id is None

---

src/spaceone/identity/manager/role_binding_manager.py
src/spaceone/identity/model/workspace_group/database.py
src/spaceone/identity/service/workspace_group_service.py

Modify exclude_unset option and database index

Modify exclude_unset option and database index

---

src/spaceone/identity/model/user_profile/request.py
src/spaceone/identity/model/user_profile/response.py
src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/workspace_service.py

When adding a workspace from A to B, update the `user_count` of workspaces

When adding a workspace from A to B, update the user_count of workspaces

---

src/spaceone/identity/manager/workspace_group_user_manager.py
src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/workspace_group_service.py
src/spaceone/identity/service/workspace_group_user_service.py
src/spaceone/identity/service/workspace_service.py

Remove code such that find Mongodb nested document

Remove code such that find Mongodb nested document

---

src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/workspace_group_service.py
src/spaceone/identity/service/workspace_group_user_service.py

Convert type when calling the add_user_name_and_state_to_users method

Convert type when calling the add_user_name_and_state_to_users method

---

src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/workspace_group_service.py

Add WorkspaceGroup object type

Add WorkspaceGroup object type

---

src/spaceone/identity/service/user_profile_service.py

Modify get_workspace_groups

---

src/spaceone/identity/service/user_profile_service.py

Modify workspace_group_info type

Modify workspace_group_info type

---

src/spaceone/identity/service/workspace_group_service.py

Modify code when workspace group users is None

Modify code when workspace group users is None

---

src/spaceone/identity/service/workspace_group_service.py

Modify code when a user is not a dict type

Modify code when a user is not a dict type

---

src/spaceone/identity/service/workspace_group_user_service.py

Modify code when updating role type of USER

Modify code when updating role type of USER

---

src/spaceone/identity/service/workspace_service.py

Delete workspace role binding when workspace group is added

Delete workspace role binding when workspace group is added

---

src/spaceone/identity/service/workspace_service.py

Modify code such that deleted original users when adding workspace to workspace group

Modify code such that deleted original users when adding workspace to workspace group

---

src/spaceone/identity/service/workspace_group_user_service.py

Can remove any user when user is a domain

Can remove any user when user is a domain

---

src/spaceone/identity/service/workspace_service.py

Modify code such that delete role binding when delete workspace

Modify code such that delete role binding when delete workspace

---

src/spaceone/identity/service/workspace_service.py

Modify code such that there are no users when creating a workspace group

Modify code such that there are no users when creating a workspace group

---

src/spaceone/identity/error/custom.py
src/spaceone/identity/manager/workspace_group_manager.py
src/spaceone/identity/service/workspace_group_service.py
src/spaceone/identity/service/workspace_group_user_service.py
src/spaceone/identity/service/workspace_service.py

Refactor all of the codes for maintenance

Refactor all of the codes for maintenance

---

src/spaceone/identity/service/workspace_group_service.py

Add return value

---

src/spaceone/identity/manager/workspace_group_manager.py

Extend old_user_ids and new_user_ids, not intialization

Extend old_user_ids and new_user_ids, not intialization

---

src/spaceone/identity/manager/workspace_group_manager.py

Update method for getting unique user_ids

Update method for getting unique user_ids

---

src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/workspace_group_service.py
src/spaceone/identity/service/workspace_group_user_service.py

Refactor get_workspace_groups method

Refactor get_workspace_groups method

---

pkg/pip_requirements.txt
src/setup.py
src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/manager/mfa_manager/__init__.py
src/spaceone/identity/manager/mfa_manager/base.py
src/spaceone/identity/manager/mfa_manager/email_mfa_manger.py
src/spaceone/identity/manager/mfa_manager/otp_mfa_manager.py
src/spaceone/identity/manager/secret_manager.py
src/spaceone/identity/manager/token_manager/mfa_token_manager.py
src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/user_profile_service.py

- Implement OTP for multi-factor authentication (MFA)

Implement OTP for multi-factor authentication (MFA)

---

src/spaceone/identity/manager/mfa_manager/otp_mfa_manager.py

- Fix error in OTP confirm when createing user_ secret_id

Fix error in OTP confirm when createing user_ secret_id

---

src/spaceone/identity/manager/mfa_manager/otp_mfa_manager.py

- Fix params error in OTP confirm when createing user_ secret_id

Fix params error in OTP confirm when createing user_ secret_id

---

src/spaceone/identity/error/error_mfa.py
src/spaceone/identity/service/token_service.py

Add mfa_type to error message in Token service issue method

Add mfa_type to error message in Token service issue method

---

src/spaceone/identity/error/error_mfa.py

Fix typo in Token issue error message when MFA required

Fix typo in Token issue error message when MFA required

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/interface/grpc/user_profile.py
src/spaceone/identity/manager/token_manager/base.py
src/spaceone/identity/model/user/database.py
src/spaceone/identity/model/user/response.py
src/spaceone/identity/model/user_profile/request.py
src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/user_service.py

- Add new feature for setting refresh timeout for domain admin user

Add new feature for setting refresh timeout for domain admin user

---

src/spaceone/identity/interface/grpc/user.py
src/spaceone/identity/interface/grpc/user_profile.py
src/spaceone/identity/manager/token_manager/base.py
src/spaceone/identity/model/user/request.py
src/spaceone/identity/model/user_profile/request.py
src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/user_service.py

- modify feature for setting refresh 'UserProfile' -> 'User'

Modify feature for setting refresh 'UserProfile' -> 'User'

---

src/spaceone/identity/manager/secret_manager.py
src/spaceone/identity/service/token_service.py

Update MFA requirement to apply only for LOCAL auth_type

Update MFA requirement to apply only for LOCAL auth_type

---

src/spaceone/identity/service/service_account_service.py
src/spaceone/identity/service/token_service.py

Fix update service account with secret

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/lib/key_generator.py
src/spaceone/identity/manager/token_manager/base.py
src/spaceone/identity/service/user_service.py

Add endpoints values at token payload

---

src/spaceone/identity/lib/key_generator.py
src/spaceone/identity/model/user_profile/response.py
src/spaceone/identity/service/user_profile_service.py

- remove endpoints at token payload

Remove endpoints at token payload

---

src/spaceone/identity/manager/token_manager/base.py

- remove unused parameter when generate token

Remove unused parameter when generate token

---

src/spaceone/identity/interface/grpc/service_account.py
src/spaceone/identity/manager/service_account_manager.py
src/spaceone/identity/model/service_account/request.py
src/spaceone/identity/service/service_account_service.py

feat: create service account analyze function for metric data.

Create service account analyze function for metric data.

---

src/spaceone/identity/manager/opsflow_manager.py
src/spaceone/identity/service/package_service.py

- add validation to package.delete

fix: add validation to package.delete

---

src/spaceone/identity/manager/mfa_manager/base.py
src/spaceone/identity/manager/mfa_manager/otp_mfa_manager.py
src/spaceone/identity/manager/token_manager/base.py

Improve email verification code generation with pyotp (SHA-256)

Improve email verification code generation with python secrets

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/error/error_authentication.py
src/spaceone/identity/service/token_service.py

- add logic to block token issue after repeated attempts

Add logic to block token issue after repeated attempts

---

src/spaceone/identity/service/token_service.py

- modify logic to block token issue after repeated attempts

Modify logic to block token issue after repeated attempts

---

src/spaceone/identity/error/error_user.py
src/spaceone/identity/interface/grpc/user_profile.py
src/spaceone/identity/manager/user_manager.py
src/spaceone/identity/model/user_profile/request.py
src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/user_profile_service.py

- add update_password api at UserProfile

Add update_password api at UserProfile

---

src/spaceone/identity/conf/global_conf.py

Modify global_conf.py

---

src/spaceone/identity/managed_resource/package/basic.yaml
src/spaceone/identity/manager/managed_resource_manager.py
src/spaceone/identity/manager/package_manager.py
src/spaceone/identity/service/package_service.py

feat: implement default package

---

src/spaceone/identity/model/__init__.py

- import package database model

refactor: import package database model

---

src/spaceone/identity/manager/endpoint_manager.py
src/spaceone/identity/model/endpoint/request.py
src/spaceone/identity/model/endpoint/response.py
src/spaceone/identity/service/endpoint_service.py

Add internal_endpoint to endpoint list

Add internal_endpoint to endpoint list

---

src/spaceone/identity/lib/key_generator.py
src/spaceone/identity/manager/token_manager/base.py
src/spaceone/identity/service/token_service.py

- add user_groups info at token payload

Add user_groups info at token payload

---

src/spaceone/identity/service/app_service.py

- fix update expired_at on token regeneration

fix update expired_at on token regeneration

---

src/spaceone/identity/service/role_binding_service.py

Fix deletion issue for role_binding with DOMAIN_ADMIN role_type

Fix deletion issue for role_binding with DOMAIN_ADMIN role_type

---

src/spaceone/identity/model/user_profile/request.py
src/spaceone/identity/service/user_profile_service.py

Remove password field from UserProfile Update

Remove password field from UserProfile Update

---

src/spaceone/identity/manager/token_manager/base.py
src/spaceone/identity/model/user_profile/request.py
src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/user_service.py

- add injected params at token when user use reset_password

Add injected params at token when user use reset_password

---

src/spaceone/identity/service/token_service.py

- grant token error when get user groups with none type error

Grant token error when get user groups with none type error

---

src/spaceone/identity/service/service_account_service.py

- remove set_query_page_limit decorator at list of sa

Remove set_query_page_limit decorator at list of sa

---

src/spaceone/identity/service/service_account_service.py

Fix error when updating Service Account name

Fix error when updating Service Account name

---

deploy/helm/Chart.yaml
deploy/helm/values.yaml

Add expiring_app_check_scheduler to helm chart

Add expiring_app_check_scheduler to helm chart

---

src/spaceone/identity/service/service_account_service.py

- remove service account query limit

Remove service account query limit

---

src/spaceone/identity/service/service_account_service.py

- remove limit for service account list

Remove limit for service account list

---

src/spaceone/identity/error/custom.py
src/spaceone/identity/model/service_account/database.py
src/spaceone/identity/model/service_account/request.py
src/spaceone/identity/model/service_account/response.py
src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/service_account_service.py

- add service account mgr id field at ServiceAccount

Add service account mgr id field at ServiceAccount

---

src/spaceone/identity/service/service_account_service.py

- Temporary comment verified user for service_mgr_id

Temporary comment verified user for service_mgr_id

---

src/spaceone/identity/template/reset_pwd_link_when_pw_forgotten_en.html
src/spaceone/identity/template/reset_pwd_link_when_pw_forgotten_ja.html
src/spaceone/identity/template/reset_pwd_link_when_pw_forgotten_ko.html

- modify link location 'text' -> 'button' at reset password template

Modify link location 'text' -> 'button' at reset password template

---

src/spaceone/identity/service/project_service.py
src/spaceone/identity/service/service_account_service.py

* update role types for project and service account creation

fix: update role types for project and service account creation

---

src/spaceone/identity/service/job_service.py

Update plugin options to include sync options

Update plugin options to include sync options

---

src/spaceone/identity/model/user/database.py
src/spaceone/identity/service/job_service.py

* rename cost retrieval methods for clarity and update logic to fetch monthly cost

refactor: rename cost retrieval methods for clarity and update logic to fetch monthly cost

---

src/spaceone/identity/interface/grpc/workspace.py
src/spaceone/identity/manager/workspace_manager.py
src/spaceone/identity/model/workspace/request.py
src/spaceone/identity/service/workspace_service.py

- [v] New feature
create workspace analyze function for metric data.

feat: create workspace analyze function for metric data.

---

src/spaceone/identity/model/user/request.py
src/spaceone/identity/service/user_service.py

fix: Change user MFA requset payload method from unstructured format to flag

---

src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/user_service.py

fix: Enable OTP permission handling

---

src/spaceone/identity/service/user_service.py

refactor: Updates MFA option for user enforce mfa

---

pkg/pip_requirements.txt
src/setup.py

chore: Updates dependency spaceone-api/core version

---

Dockerfile
src/spaceone/identity/model/user/request.py
src/spaceone/identity/service/token_service.py

feat: add token grant type restriction logic in TokenService 

---

src/spaceone/identity/error/error_mfa.py
src/spaceone/identity/service/token_service.py

fix: prevent refresh token issuance when MFA enforcement is active

---

src/spaceone/identity/service/token_service.py

add logging for test in Dev environment

test: Adds debug logging for token generation

---

src/spaceone/identity/service/token_service.py
src/spaceone/identity/service/user_service.py

fix: remove unnecessary logging in TokenService

---

src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/user_service.py

feat: Enhances role binding deletion checks

---

src/spaceone/identity/error/error_mfa.py
src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/user_service.py

chore: Imports SecretManager for OTP checks

---

src/spaceone/identity/manager/token_manager/mfa_token_manager.py
src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/user_service.py

feat: Updates user state after MFA verification

---

src/spaceone/identity/service/token_service.py

refactor: Change MFA activation conditions

---

src/spaceone/identity/manager/role_binding_manager.py
src/spaceone/identity/manager/workspace_manager.py
src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/workspace_service.py

feat: resolve circular dependency and improve workspace user count synchronization

---

src/spaceone/identity/manager/role_binding_manager.py
src/spaceone/identity/manager/workspace_manager.py
src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/workspace_group_service.py
src/spaceone/identity/service/workspace_service.py

refactor: move workspace delete business logic from manager to service

---

src/spaceone/identity/service/user_profile_service.py
src/spaceone/identity/service/user_service.py

refactor: Refactors UserProfile MFA state handling

---

src/spaceone/identity/manager/token_manager/local_token_manager.py
src/spaceone/identity/service/token_service.py

Improve logging for authentication and token issue

Improve logging for authentication and token issue

---

src/spaceone/identity/service/domain_service.py
src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/system_service.py
src/spaceone/identity/service/user_service.py
src/spaceone/identity/service/workspace_group_service.py
src/spaceone/identity/service/workspace_service.py

fix: Avoids unnecessary workspace retrieval
